### ISSUE TITLE
I want to know the price of Kai protocol TVL.

### ISSUE THREAD

**Issue by ahnyongkwon** [kaiprotocol/kaiprotocol-audit#1]
2021-07-17 , 08:45am 
kaiprotocol.fi
tvl $69,127,486
skai total $28,441,494
kai total $14,389,667

skai total + kai total = tvl 

I'd like to know why TVL totals are wrong.
Also, I would like to know how to calculate tvL

**Comment by kaiprotocol** [comment]
It is the sum of KLAYswap's Kai Protocol official pool TVL and sKAI single deposit TVL.

Total TVL = [KUSDT - KAI] pair TVL + [KLAY - sKAI] pair TVL + [KSP - sKAI] pair TVL + Stake sKAI TVL
